spring.application.name=tabz

# H2 database
spring.datasource.url=jdbc:h2:mem:tabzdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#app.base-url=http://192.168.2.12:8080
 app.base-url=http://localhost:8080
