spring.application.name=tabz


## DATABASE

# Postgres database
spring.datasource.url=jdbc:postgresql://localhost:5432/tabz
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


## NETWORK
#app.base-url=http://192.168.2.12:8080
app.base-url=http://localhost:8080
